### ISSUE TITLE
Compatibility report fails when run against a NUnit 2.6.4 project

### ISSUE THREAD

**Issue by mikkelbu** [nunit-legacy/nunitv2#56]
I just tried to run the  compatibility report against a dll compiled with NUnit 2.6.4 and it failed with a NRE. The problem is that the code tries to convert the value of the property `LegacyResultUsed` to a boolean, but `LegacyResultUsed` only exists in 2.6.5 and forward. I think that either the compatibility report should be made more robust and give a better error or this should be documented somewhere (I prefer the first solution).
```
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object.

Server stack trace:
   at NUnit.Core.Compatibility.CheckAttributes(ICustomAttributeProvider provider, String location) in C:\Temp\2.6.7\nunitv2\src\NUnitCore\core\Compatibility.cs:line 182
   at NUnit.Core.Compatibility.CheckAttributes(MemberInfo member) in C:\Temp\2.6.7\nunitv2\src\NUnitCore\core\Compatibility.cs:line 134
   at NUnit.Core.Compatibility.CheckAttributes(Assembly assembly) in C:\Temp\2.6.7\nunitv2\src\NUnitCore\core\Compatibility.cs:line 123
   at NUnit.Core.Builders.TestAssemblyBuilder.Build(String assemblyName, Boolean autoSuites, Boolean checkCompatibility) in C:\Temp\2.6.7\nunitv2\src\NUnitCore\core\Builders\TestAssemblyBuilder.cs:line 117
...
```

**Comment by CharliePoole** [comment]
The nunit.core and nunit.framework assemblies have to match as written. That's a departure from normal V2 practice, where the runner is backward compatible with older frameworks. I'll look into restoring that convention in the morning (five or six hours). Otherwise, I think we need an error if you use the option with an older framework.

**Comment by CharliePoole** [comment]
Problem is smaller than I feared. The attributes are correctly retrieved using reflection. However, I carelessly applied a (bool) cast to what might be a null result.
